### ISSUE TITLE
 The Question About the Usage of Source Domain Data

### ISSUE THREAD

**Issue by lixiangcog** [Chen-Ziyang/VPTTA#4]
According to my understanding, in the Statistics Alignment step, this method still utilizes the source domain data and its labels. 

So, it's not entirely source-free, is it?

**Comment by Chen-Ziyang** [comment]
Thanks for this concern.
In the inference phase, we introduce the source statistics by using the running_mean and running_var stored within the BN layers.
Therefore,  there is no need to utilize source domain data or its labels during inference.
The related code can be found in [utils/convert.py](https://github.com/Chen-Ziyang/VPTTA/blob/main/OPTIC/utils/convert.py).
