### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by H-CODE6** [Chen-Ziyang/VPTTA#7]
Dear author, thank you very much for opening up numerous projects. We are very interested in them and have conducted experimental reproduction of the paper: TriLA: Triple Level Alignment based Unsupervised Domain Adaptation for Joint Segmentation of Optic Disc and Optic Cup（ https://github.com/Chen-Ziyang/TriLA?tab=readme -OV file), it was found that the main. py file is missing the train-NoAdapt file, so the code cannot be run. We look forward to your timely upload of this part of the code. Thank you very much and look forward to your reply!

**Comment by Chen-Ziyang** [comment]
Thank you for reminding this. We have uploaded the missing file.

**Comment by H-CODE6** [comment]
Thank you very much for your reply, but it seems that there are still some errors during training (eg: config. model_maath=os. path. join (config. path_stave_madel, loss_name, config. load_time), TypeError: join() argument must be str or bytes, not 'NoneType'）， We look forward to your timely code improvement to ensure that the final overall code can run successfully. Thank you very much.

**Comment by Chen-Ziyang** [comment]
Delete the default value of 'reload' as follows.
`parser.add_argument('--reload', type=int)`

**Comment by H-CODE6** [comment]
Thank you very much for your reply.We have replicated many projects and found that in TirD（ https://github.com/Chen-Ziyang/TriD ）After testing on the project, we were unable to obtain the visualization results shown in the paper. What we obtained were only gray background OC and OD results. How did we obtain the colored visualization of the results in your paper? Can we open source this part of the code for us to implement? Looking forward to your reply.

**Comment by H-CODE6** [comment]
Thank you very much for your reply. It seems that this error still exists during the training process (lfda_data=self. lfda. module. activate (self. lfda. fda_beta). data), AttributeError: 'LFDA' object has no attribute 'module'）。 Looking forward to your repair

**Comment by Chen-Ziyang** [comment]
Please use the following codes to replace lines 326-329 in "train_DA.py".
In our practice, we use two NVIDIA 2080Ti GPUs to run the codes.

    try:
        lfda_data = self.lfda.module.activate(self.lfda.module.fda_beta).data   #multi gpus
    except:
        lfda_data = self.lfda.activate(self.lfda.fda_beta).data   #single gpu

**Comment by H-CODE6** [comment]
Thank you very much for your reply. We have successfully run the code, but after the final training, no. pth files were generated in the results folder, so we cannot proceed with testing. We are unsure of the reason and look forward to your fix. Thank you very much!
